### PR TITLE
Style Route Options

### PR DESCRIPTION
**Pull request by AconexOfficial**
### Description

This is the Pull Request Template for the Oeffis Project

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [x] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [x] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [x] No tests required
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Escowei98** [comment]
image

Route details and Button overlap if route-details are to long

**Comment by Escowei98** [comment]
image

The button in the prior page (route-results) ist sticky, maybe we can make this on sticky too, to have more consistency

**Comment by Escowei98** [comment]
image

A little padding or text-break would be nice to make this more readable

**Review by Escowei98 — CHANGES_REQUESTED** [review]
https://github.com/Oeffis/Oeffis/pull/484#issuecomment-1924773195
https://github.com/Oeffis/Oeffis/pull/484#issuecomment-1924774786

**Comment by LaraBiss** [comment]
tmp

I changed the appereance of the "back to route planner"-button so it's matching the wireframes. 
Thought you maybe missed this while merging. If you want to keep the floating button just ignore this comment.

**Comment by AconexOfficial** [comment]
> image
> 
> A little padding or text-break would be nice to make this more readable

Should be resolved in Fix Route Detail Grid
[#526](https://github.com/Oeffis/Oeffis/issues/526)

**Comment by AconexOfficial** [comment]
> tmp
> 
> I changed the appereance of the "back to route planner"-button so it's matching the wireframes. Thought you maybe missed this while merging. If you want to keep the floating button just ignore this comment.

Removed the padding, so the button will now keep the look from main

**Review by Escowei98 — APPROVED** [review]

**Pull request merged**
