### PR TITLE
Feature/380 dbo schema historic data

### PR DESCRIPTION
**Pull request by JaJako**
### Description

Introduces DBO schema for historic data. Solves #380.

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [x] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [ ] Frontend
- [x] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [x] No tests required
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JaJako** [comment]
@timvahlbrock Is your commit on 380's branch intentional?

**Comment by timvahlbrock** [comment]
> @timvahlbrock Is your commit on 380's branch intentional?

Yes it was. But you're probably right, this doesn't belong here. Should I remove it or will you?

**Comment by JaJako** [comment]
@timvahlbrock @Paulomart So I finally found a solution, so that the relations (using eager) are working. Seems to be problem was, that referenced fields did not match because e.g. referenced `vrrTimetableVersion` field was an object, but source to compare in join was the `vrr_timetable_version_id` (some string). Of course there was no match. Now for every field with relation there is the original id field from the table + an extra field storing the relation's object/entity. 

Only place this is not working is `StopEntry` because there is a (theoretically) circular relation with `parent_station` resulting in StackOverflow error when resolving some stop entity (even if the stops in practice has just one parent each). So there is the only lazy relation (using `Promise`).
```
  @IsString()
  @IsOptional()
  @Column({ name: "parent_station", type: "text", nullable: true })
  public readonly parentStationId?: string;

  @IsInstance(StopEntry)
  @IsOptional()
  @ManyToOne(() => StopEntry, { lazy: true, nullable: true })
  @JoinColumn([
    { name: "parent_station", referencedColumnName: "stopId" },
    { name: "vrr_timetable_version_id", referencedColumnName: "vrrTimetableVersionId" }
  ])
  public readonly parentStation?: Promise<StopEntry>;
```

**Comment by JaJako** [comment]
But problem with the lazy parent relation: When I use `await` to get Promise result (the parent stop) `undefined` gets returned in my test scenario (while there should be a parent). Dunno why this is not working. Maybe you can take a closer look at that specific relation when reviewing.

**Comment by JaJako** [comment]
If you like to use the code I have tested the relations with, just temporarily replace `HistoricDataService` and trigger method:

<details>
  <summary>HistoricDataService</summary

```
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { DelayEntry } from "historicData/entity/delayEntry.entity";
import { Repository } from "typeorm";
import { AgencyEntry } from "../entity/agencyEntry.entity";
import { CalendarDateEntry } from "../entity/calendarDateEntry.entity";
import { CalendarEntry } from "../entity/calendarEntry.entity";
import { FeedInfoEntry } from "../entity/feedInfoEntry.entity";
import { RouteEntry } from "../entity/routeEntry.entity";
import { ShapeEntry } from "../entity/shapeEntry.entity";
import { StopEntry } from "../entity/stopEntry.entity";
import { StopTimeEntry } from "../entity/stopTimeEntry.entity";
import { TransferEntry, TransferType } from "../entity/transferEntry.entity";
import { TripEntry } from "../entity/tripEntry.entity";
import { VrrTimetableVersionEntry } from "../entity/vrrTimetableVersionEntry.entity";

@Injectable()
export class HistoricDataService {
  public constructor(
    @InjectRepository(AgencyEntry)
    private readonly agencyEntryRepository: Repository<AgencyEntry>,
    @InjectRepository(CalendarEntry)
    private readonly calendarEntryRepository: Repository<CalendarEntry>,
    @InjectRepository(CalendarDateEntry)
    private readonly calendarDateEntryRepository: Repository<CalendarDateEntry>,
    @InjectRepository(DelayEntry)
    private readonly delayEntryRepository: Repository<DelayEntry>,
    @InjectRepository(FeedInfoEntry)
    private readonly feedInfoEntryRepository: Repository<FeedInfoEntry>,
    @InjectRepository(RouteEntry)
    private readonly routeEntryRepository: Repository<RouteEntry>,
    @InjectRepository(ShapeEntry)
    private readonly shapeEntryRepository: Repository<ShapeEntry>,
    @InjectRepository(StopEntry)
    private readonly stopEntryRepository: Repository<StopEntry>,
    @InjectRepository(StopTimeEntry)
    private readonly stopTimeEntryRepository: Repository<StopTimeEntry>,
    @InjectRepository(TransferEntry)
    private readonly transferEntryRepository: Repository<TransferEntry>,
    @InjectRepository(TripEntry)
    private readonly tripEntryRepository: Repository<TripEntry>,
    @InjectRepository(VrrTimetableVersionEntry)
    private readonly vrrTimetableVersionEntryRepository: Repository<VrrTimetableVersionEntry>
  ) { }

  public async getDelayEntryCount(): Promise<number> {

    // Agency: ok
    const someAgencyData = await this.agencyEntryRepository.findBy({ agencyId: "bgs-30" });
    //console.log(someAgencyData);
    console.assert(someAgencyData[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // CalendarDate: ok
    const calendarDateEntry = await this.calendarDateEntryRepository.findBy({ serviceId: "Special" });
    //console.log(calendarDateEntry);
    console.assert(calendarDateEntry[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // Calendar: ok
    const calendarEntry = await this.calendarEntryRepository.findBy({ serviceId: "Special" });
    //console.log(calendarEntry);
    console.assert(calendarEntry[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // Delay: ok
    const someDelayData = await this.delayEntryRepository.findBy({ id: 50 });
    //console.log(someDelayData);
    console.assert(someDelayData[0].stop?.stopName === "DU-Friedrich-Ebert-Str.");
    console.assert(someDelayData[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // FeedInfo: ok
    const feedInfoEntry = await this.feedInfoEntryRepository.findBy({ feedPublisherName: "VRR" });
    //console.log(feedInfoEntry);
    console.assert(feedInfoEntry[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // Route: ok
    const route = await this.routeEntryRepository.findBy({ routeShortName: "302" });
    //console.log(route);
    const routeAgency = route[0].agency;
    console.assert(routeAgency.agencyName === "Bochum-Gelsenkirchener Strassenbahn AG");
    console.assert(route[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // Shape: no data to test with

    // StopTime: ok
    const stopTime = await this.stopTimeEntryRepository.findBy({ tripId: "bgs-30-306-1-12-4-H-0-Special-3207-61" });
    //console.log(stopTime);
    console.assert(stopTime[0].stop.stopName === "Herne Hannibalstr.");
    console.assert(stopTime[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // Stop: Waiting for lazy relation (Promise) does not return related object (undefined only). TODO
    const someStopData = await this.stopEntryRepository.findBy({ stopName: "Gelsenkirchen Hbf" });
    //console.log(someStopData);
    console.assert((await someStopData[0].parentStation)?.stopName === "Gelsenkirchen Hbf");
    console.assert(someStopData[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // Transfer: ok
    const transfer = await this.transferEntryRepository.findBy({ transferType: TransferType.minTransferTime });
    //console.log(transfer);
    console.assert(transfer[0].fromStop.stopName === "DO Adelenstraße");
    console.assert(transfer[0].toStop.stopName === "DO Adelenstraße");
    console.assert(transfer[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    // Trip: ok
    const trip = await this.tripEntryRepository.findBy({ tripId: "bgs-30-306-1-12-4-H-0-Special-3175-1" });
    //console.log(trip);
    console.assert(trip[0].service.serviceId === "Special");
    console.assert(trip[0].route.routeShortName === "306");
    console.assert(trip[0].vrrTimetableVersion.vrrTimetableVersionId === 1);

    console.log("Testing relations finished.");

    return this.delayEntryRepository.count();
  }
}
```

</details>

**Review by timvahlbrock — APPROVED** [review]

**Pull request merged**
