### PR TITLE
Improve performance of leg stats calculation

### PR DESCRIPTION
**Pull request by timvahlbrock**
### Description

This is the Pull Request Template for the Oeffis Project

## Checklist

- [ ] My code follows the style guidelines
- [ ] I have documented my code
- [ ] My changes generate no new warnings
- [ ] I have linked the Issue
- [ ] The Pull Request covers all the Checkpoints from the tagged Issue
- [ ] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [ ] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [ ] No tests required
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by timvahlbrock** [comment]
@Paulomart we might add some more indices on this one. How about another hash indices on `trip_id` and `planned`?

**Comment by timvahlbrock** [comment]
> @Paulomart we might add some more indices on this one. How about another hash indices on `trip_id` and `planned`?

However, I think the greatest performance boost will come from cacheing

**Comment by Paulomart** [comment]
> @Paulomart we might add some more indices on this one. How about another hash indices on trip_id and planned?

Sure I can do that.

**Comment by timvahlbrock** [comment]
> @Paulomart . With the caching we're down to 1.2 to 1.4 seconds for a request (including querying the VRR api). I would say that's okay for now, assuming we integrate a loading spinner.

On the other hand, I removed the caching again and checked the times again. No significant difference. So the main acceleration seems to be created by the indexes. @Paulomart maybe you can check you tool again to find any more optimisation potential?

**Comment by timvahlbrock** [comment]
DataGrip shows actual query performance is down to 30ms. The actual slow down is the VRR API.

**Review by Paulomart — APPROVED** [review]

**Pull request merged**
