### PR TITLE
Feature/466 investigate crawled data

### LINKED ISSUE #466: Investigate/test data requested/collected by crawler (especially used format of parent_stop_id)
There are different formats used for id of parent stops. `stop` table from vrr timetable data uses format with suffix `_Parent`. However stop id used for stop parent in queried journeys does not have this format with suffix but use "NVBW_HST_DHID" format.

As far as I understand crawler uses format with `_Parent` suffix for crawling data and writes those formatted stop_ids to `historic_data` table's `parent_stop_id`. So there is a mismatch when searching for delay data by parent stop id in `historic_data` table with id of parent stop from a journey. (But this should not be a problem anymore after pending fix from #437).

What should be checked here:
- [x] What parent_stop_ids (with received data) is the crawler adding to `historic_data` table (format-wise).
- [x] Is VRR supporting format with `_Parent` suffix when requesting delay data.

### PR DESCRIPTION
**Pull request by JaJako**
### Description

Investigates crawled historic_data + suggests change to crawler. Closes #466.

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [x] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [ ] Frontend
- [ ] Backend
- [ ] Github
- [x] Root

## If tests are required did you make them?

- [x] No tests required
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JaJako** [comment]
I've investigated the crawled data and found stops that should get crawled but where there are no entries for in `historic_data`. One big portion are all stops using a hierarchy (the parent all have that "_Parent" suffix). Those stops (like "Bochum Hbf", "Düsseldorf Hbf") are not included in `historic_data` anymore. 

Last entries are from around begin of October (before we changed to requesting parent stops only I think). I would suggest VRR does not know how to handle stop_ids in "_Parent" format - so no data for these. As VRR uses "NVBW_HST_DHID" of those parents when planning journeys, I suggest we should use "NVBW_HST_DHID" to request delay data, too.

My suggestion (part of the PR): using DISTINCT "NVBW_HST_DHID" in general for requesting delay data (instead of stop_id). I found some other cases where this would be beneficial too: "Osnabrück Hbf" for example does not has any hierarchy but three separate stop entries. At the moment we would request all three "Osnabrück Hbf" individually; using DISTINCT "NVBW_HST_DHID" we can "group" these (without them having a hierarchy) and requesting delay data once only.

**Comment by JaJako** [comment]
See added Jupyter notebook for details.

**Comment by timvahlbrock** [comment]
> At the moment we would request all three "Osnabrück Hbf" individually; using DISTINCT "NVBW_HST_DHID" we can "group" these (without them having a hierarchy) and requesting delay data once only.

Did you test wether using the NVBW_HST_DHID of Osnabrück actually returns values?

**Comment by JaJako** [comment]
> > At the moment we would request all three "Osnabrück Hbf" individually; using DISTINCT "NVBW_HST_DHID" we can "group" these (without them having a hierarchy) and requesting delay data once only.
> 
> Did you test wether using the NVBW_HST_DHID of Osnabrück actually returns values?

Not with the crawler itself. But adding NVBW_HST_DHID of Osnabrück as URL origin/destination param in our route planner, did resolve to "Osnabrück Hbf" - or searching and selecting "Osnabrück Hbf" via the search modal also uses "NVBW_HST_DHID" (de:03404:71609 in this case) afterward in url.

Assuming possible input (formats) of "route planner VRR api" and "stop times VRR api" (crawler) are the same: What is working in route planner are NVBW_HST_DHID and non-parent stop_ids. But parent stop_ids (those ending with "_Parent") are not working (encoded into URL param), which matches with the types of stops we have crawled data for and which we haven´t.

**Comment by JaJako** [comment]
> > > At the moment we would request all three "Osnabrück Hbf" individually; using DISTINCT "NVBW_HST_DHID" we can "group" these (without them having a hierarchy) and requesting delay data once only.
> > 
> > 
> > Did you test wether using the NVBW_HST_DHID of Osnabrück actually returns values?
> 
> Not with the crawler itself. But adding NVBW_HST_DHID of Osnabrück as URL origin/destination param in our route planner, did resolve to "Osnabrück Hbf" - or searching and selecting "Osnabrück Hbf" via the search modal also uses "NVBW_HST_DHID" (de:03404:71609 in this case) afterward in url.
> 
> Assuming possible input (formats) of "route planner VRR api" and "stop times VRR api" (crawler) are the same: What is working in route planner are NVBW_HST_DHID and non-parent stop_ids. But parent stop_ids (those ending with "_Parent") are not working (encoded into URL param), which matches with the types of stops we have crawled data for and which we haven´t.

Correction: parent stop_ids with "_Parent" does seem to work via VRR route planner API in theory but returns error "Multiple locations found with id", resulting in no stop being selected.

**Pull request merged**
