### PR TITLE
Fix/ci errors

### PR DESCRIPTION
**Pull request by timvahlbrock**
### Description

This is the Pull Request Template for the Oeffis Project

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [x] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [ ] Frontend
- [ ] Backend
- [x] Github
- [ ] Root

## If tests are required did you make them?

- [x] No tests required
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Paulomart** [comment]
@timvahlbrock cant we get the automerge working?

**Comment by timvahlbrock** [comment]
> @timvahlbrock cant we get the automerge working?

feel free. The current problem is a bit of dependabot permissions, the usage of merge queues. Dependabot isn't allowed to merge itself and hasn't access to our secrets to get a sufficient token. We could use other auto-merge tools, but I don't know if they work with merge queues. Feel free to experiment, but this fix is to prevent all the pipelines on the Dependabot PRs from failing.

**Comment by Paulomart** [comment]
I see, then lets merge this and try again in the future.

**Review by Paulomart — APPROVED** [review]

**Comment by timvahlbrock** [comment]
> I see, then lets merge this and try again in the future.

That was the plan. However, I also saw discussions on auto-merges being a security risk. We should keep that in mind. Dependabot is preparing a feature where all updates are collected in one PR. Maybe that's easy enough for us.

**Pull request merged**
