### PR TITLE
Adaptions for K8 Deployment

### PR DESCRIPTION
**Pull request by timvahlbrock**
### Description

Make adaptions for K8s deployment.

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [ ] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [x] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [ ] No tests required
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by timvahlbrock** [comment]
@Paulomart checks passing again. PR is ready for review.

**Comment by Paulomart** [comment]
@timvahlbrock didnt we say we don't want to use the proxy feature and instead host both components on different hostnames / ports?

**Comment by timvahlbrock** [comment]
The proxy is only used in development when using the vite server.

**Comment by Paulomart** [comment]
@timvahlbrock I dont see why this is required. We should be eager to keep prd and dev setup the sam.e

**Comment by timvahlbrock** [comment]
> @timvahlbrock I dont see why this is required. We should be eager to keep prd and dev setup the sam.e

fair. reverted

**Review by Paulomart — DISMISSED** [review]

**Review by Paulomart — APPROVED** [review]

**Pull request merged**
