### PR TITLE
Create Start/Destination Modal

### PR DESCRIPTION
**Pull request by timvahlbrock**
### Description

The start and destination input still requires the implementation of a start and destination modal. This PR should address that.

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [x] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [x] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [ ] No tests required
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by timvahlbrock** [comment]
@AconexOfficial This is all that I'll be able to do today, feel free to continue if you have some time.

**Comment by Paulomart** [comment]
I modified the input a little:

https://github.com/Oeffis/Oeffis/assets/4148404/a2d461c6-affc-439c-a028-f59d662a840c

**Comment by Paulomart** [comment]
@timvahlbrock maybe you can help getting the e2e tests going again? :)

**Comment by timvahlbrock** [comment]
> @timvahlbrock maybe you can help getting the e2e tests going again? :)

The problem is: You modified the step in the feature file isReachable.feature, but did not alter the name of the step definition in isReachable.ts . The feature file only describes the structure and order of the steps, but the stepDefinition files describe, what each step means. There actually is a vscode extension that is able to link steps with their step definitions, but it is currently not working because of bugs in a third party dependency.

**Comment by timvahlbrock** [comment]
Also: The currently implementation does not work for me.

**Comment by Paulomart** [comment]
Something is mad:

grafik

(Looks way better)

**Comment by timvahlbrock** [comment]
> Something is mad:
> 
> grafik
> (Looks way better)

will take a look at this in 5 minutes. just adding another e2e test for the destination input

**Comment by timvahlbrock** [comment]
> > Something is mad:
> > grafik
> > (Looks way better)
> 
> will take a look at this in 5 minutes. just adding another e2e test for the destination input

@Paulomart Done. Ionic no longer wants separate Labels when being used with IonInput, but rather usage of label properties on the IonInput itself. Later E2E Tests might benefit from Origin and Destination being different, but that can be dealt with when its required.

**Review by Paulomart — APPROVED** [review]

**Pull request merged**
