### PR TITLE
Encode origin and destination of route in url

### LINKED ISSUE #95: Encode start and destination nodes as url parameters in route view.

### PR DESCRIPTION
**Pull request by Paulomart**
Closes #95

## Checklist

- [ ] My code follows the style guidelines
- [ ] I have documented my code
- [ ] My changes generate no new warnings
- [ ] I have linked the Issue
- [ ] The Pull Request covers all the Checkpoints from the tagged Issue
- [ ] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [ ] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [ ] No tests required
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by timvahlbrock** [comment]
I don't like the Implementation of this as JSON within the URL. How about using IDs? Then the URL would stay human readable and more visually pleasing (e.g. in messengers)

**Comment by Paulomart** [comment]
> I don't like the Implementation of this as JSON within the URL. How about using IDs? Then the URL would stay human readable and more visually pleasing (e.g. in messengers)

Yeah I thought about that. The main problem with this is it would require resolving the ids to the actual stop objects. To do this the client would need to request the full objects. This would introduce a more complicated state when loading the component.

**Comment by timvahlbrock** [comment]
> > I don't like the Implementation of this as JSON within the URL. How about using IDs? Then the URL would stay human readable and more visually pleasing (e.g. in messengers)
> 
> 
> 
> Yeah I thought about that. The main problem with this is it would require resolving the ids to the actual stop objects. To do this the client would need to request the full objects. This would introduce a more complicated state when loading the component.  

But with this approach your url suddenly contains information that can cause problems at later point of time, when the data changes.

**Comment by Paulomart** [comment]
@timvahlbrock e4cde9e

**Comment by timvahlbrock** [comment]
> @timvahlbrock [ccb9add](https://github.com/Oeffis/Oeffis/commit/ccb9add294dffe773480ec19b5d1b662ca92e264)
> 
> Ive implemented the id approche in the url

I see what you mean by more complexity. But maybe we get refactor some of this out. Is there an async version of useState?

**Comment by Paulomart** [comment]
@timvahlbrock 

> But maybe we get refactor some of this out. 

Its not getting better then this: 91d111aed0d0e2015cd3104c08848a4b8ee00a47

> Is there an async version of useState?

No

**Review by timvahlbrock — APPROVED** [review]

**Pull request merged**
